server:
   port: 8099
   
eureka:
  client:
    #registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:
   uaa:
      path: /uaa/**
      sensitive-headers:
      service-id: AUTH-SERVER 
   crud:
      path: /micro-crud/**
      sensitive-headers:
      #service-id: MICRO-CRUD
      url: http://localhost:8080/
   cr:
      path: /micro-cr/**
      sensitive-headers:
      service-id: MICRO-CR
   nodejs:
      path: /nodejs/**
      url: http://localhost:3000
